# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Create Deployment Bundle
      run: |
          mkdir -p deployment/build
          cp -r build/* deployment/
    - name: Publish Deployment Artifact
      uses: actions/upload-artifact@v4
      with:
          name: deployment-artifact
          path: ${{github.workspace}}/deployment
  deploy:
    needs: [build]
    name: Deploy to dev Environment
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Deployment Artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-artifact
      - name: list files
        run: |
           ls
     
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
          
      - name: Deploy to AWS CodeDeploy
        run: |
          aws s3 cp ./ s3://skmstaticwebpage/ --recursive
